"""Print job workflow: file uploads, quota enforcement, reject/cancel, filament.

The shared admin fixtures are superusers (printing:admin); mentors are built
with tests.integration.test_security_scoping._mentor and hold printing:read and
printing:write for their own team only.
"""

import io
import struct
import zipfile

import pytest
from sqlalchemy import select

from core.audit import AuditLog
from modules.printing import files
from modules.printing.models import PrintJob, TeamSeasonPrintQuota
from tests.integration.test_security_scoping import _mentor

MENTOR_PERMS = ["printing:read", "printing:write"]


def _binary_stl(triangles: int = 2) -> bytes:
    # Deliberately starts with "solid" like many exporters' binary headers.
    header = b"solid binary exported".ljust(80, b" ")
    return header + struct.pack("<I", triangles) + b"\x00" * (50 * triangles)


def _three_mf() -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr("3D/3dmodel.model", "<model/>")
    return buffer.getvalue()


VALID_FILES = {
    "part.stl": _binary_stl(),
    "ascii.stl": b"solid part\n facet normal 0 0 1\n endfacet\nendsolid part\n",
    "project.3mf": _three_mf(),
    "mesh.obj": b"# exported\nmtllib a.mtl\nv 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 3\n",
    "slice.gcode": b"; generated by PrusaSlicer\nG28\nG1 X10 Y10\n",
    "slice.bgcode": b"GCDE\x01\x00\x00\x00" + b"\x00" * 32,
}


async def _create(client, headers, team, season, **extra):
    payload = {"team_id": team.id, "season_id": season.id, "file_name": "part.stl", **extra}
    return await client.post("/api/printing/jobs", headers=headers, json=payload)


async def _upload(client, headers, job_id, name, content):
    return await client.post(
        f"/api/printing/jobs/{job_id}/file",
        headers=headers,
        files={"file": (name, content, "application/octet-stream")},
    )


async def _complete(client, headers, job_id, **extra):
    await client.put(f"/api/printing/jobs/{job_id}/approve", headers=headers)
    await client.patch(f"/api/printing/jobs/{job_id}", headers=headers, json={"status": "queued"})
    return await client.patch(
        f"/api/printing/jobs/{job_id}", headers=headers, json={"status": "completed", **extra}
    )


@pytest.fixture
async def rival(db):
    from modules.teams.models import Team

    other = Team(name="Rival", team_number="RIV-1", country="AT")
    db.add(other)
    await db.commit()
    return other


# ── File upload ─────────────────────────────────────────────────────────────


class TestFileUpload:
    @pytest.mark.asyncio
    @pytest.mark.parametrize("name", sorted(VALID_FILES))
    async def test_accepts_supported_formats_and_downloads(
        self, client, auth_headers, team, season, name
    ):
        job = (await _create(client, auth_headers, team, season)).json()
        resp = await _upload(client, auth_headers, job["id"], name, VALID_FILES[name])
        assert resp.status_code == 200, resp.text
        body = resp.json()
        assert body["file_name"] == name
        assert body["file_size_bytes"] == len(VALID_FILES[name])
        assert body["file_url"] == f"/api/printing/jobs/{job['id']}/file"

        download = await client.get(f"/api/printing/jobs/{job['id']}/file", headers=auth_headers)
        assert download.status_code == 200
        assert download.content == VALID_FILES[name]
        assert download.headers["content-disposition"].startswith("attachment")
        assert download.headers["content-type"] == "application/octet-stream"

    @pytest.mark.asyncio
    @pytest.mark.parametrize(
        ("name", "content"),
        [
            ("evil.exe", b"MZ\x90\x00"),
            ("page.html", b"<html></html>"),
            ("fake.3mf", b"not a zip at all"),
            ("fake.bgcode", b"; text gcode"),
            ("fake.stl", b"\x00\x01\x02 random binary that is no stl"),
            ("fake.obj", b"\x89PNG\r\n\x1a\n\x00\x00"),
            ("fake.gcode", b"G28\x00\x00binary"),
            ("empty.stl", b""),
        ],
    )
    async def test_rejects_wrong_type_or_content(
        self, client, auth_headers, team, season, name, content
    ):
        job = (await _create(client, auth_headers, team, season)).json()
        resp = await _upload(client, auth_headers, job["id"], name, content)
        assert resp.status_code == 422, resp.text
        assert not files.job_dir(job["id"]).exists() or not any(
            p for p in files.job_dir(job["id"]).iterdir() if not p.name.startswith(".")
        )

    @pytest.mark.asyncio
    async def test_size_limit(self, client, auth_headers, team, season, monkeypatch):
        monkeypatch.setattr(files, "MAX_PRINT_FILE_MB", 0)
        job = (await _create(client, auth_headers, team, season)).json()
        resp = await _upload(client, auth_headers, job["id"], "part.stl", _binary_stl())
        assert resp.status_code == 422
        assert "too large" in resp.json()["message"]

    @pytest.mark.asyncio
    async def test_traversal_name_stays_in_job_folder(self, client, auth_headers, team, season):
        job = (await _create(client, auth_headers, team, season)).json()
        resp = await _upload(
            client, auth_headers, job["id"], "../../../etc/part.stl", _binary_stl()
        )
        assert resp.status_code == 200
        assert resp.json()["file_name"] == "part.stl"
        assert (files.job_dir(job["id"]) / "part.stl").is_file()

    @pytest.mark.asyncio
    async def test_replacing_removes_previous_file(self, client, auth_headers, team, season, db):
        job = (await _create(client, auth_headers, team, season)).json()
        await _upload(client, auth_headers, job["id"], "first.stl", _binary_stl())
        await _upload(client, auth_headers, job["id"], "second.3mf", _three_mf())
        names = sorted(p.name for p in files.job_dir(job["id"]).iterdir())
        assert names == ["second.3mf"]
        row = await db.get(PrintJob, job["id"])
        assert row.file_path == f"printing/{job['id']}/second.3mf"

    @pytest.mark.asyncio
    async def test_download_without_file_is_404(self, client, auth_headers, team, season):
        job = (await _create(client, auth_headers, team, season)).json()
        resp = await client.get(f"/api/printing/jobs/{job['id']}/file", headers=auth_headers)
        assert resp.status_code == 404

    @pytest.mark.asyncio
    async def test_mentor_own_team_only(self, client, db, team, rival, season, auth_headers):
        _, mentor = await _mentor(db, team, MENTOR_PERMS)
        own = (await _create(client, mentor, team, season)).json()
        foreign = (await _create(client, auth_headers, rival, season)).json()
        assert (await _upload(client, mentor, own["id"], "a.stl", _binary_stl())).status_code == 200
        assert (
            await client.get(f"/api/printing/jobs/{own['id']}/file", headers=mentor)
        ).status_code == 200

        await _upload(client, auth_headers, foreign["id"], "b.stl", _binary_stl())
        up = await _upload(client, mentor, foreign["id"], "x.stl", _binary_stl())
        assert up.status_code == 404
        down = await client.get(f"/api/printing/jobs/{foreign['id']}/file", headers=mentor)
        assert down.status_code == 404
        assert (
            await client.get(f"/api/printing/jobs/{foreign['id']}", headers=mentor)
        ).status_code == 404

    @pytest.mark.asyncio
    async def test_team_cannot_replace_file_after_approval(
        self, client, db, team, season, auth_headers
    ):
        _, mentor = await _mentor(db, team, MENTOR_PERMS)
        job = (await _create(client, mentor, team, season)).json()
        await client.put(f"/api/printing/jobs/{job['id']}/approve", headers=auth_headers)
        resp = await _upload(client, mentor, job["id"], "late.stl", _binary_stl())
        assert resp.status_code == 409
        # Organizers may still swap the file before printing starts.
        assert (
            await _upload(client, auth_headers, job["id"], "fix.stl", _binary_stl())
        ).status_code == 200


# ── Quotas ──────────────────────────────────────────────────────────────────


class TestQuotaEnforcement:
    @pytest.mark.asyncio
    async def test_open_jobs_count_toward_hard_limit(self, client, auth_headers, team, season):
        for _ in range(4):  # default max_parts == 4, none completed
            assert (await _create(client, auth_headers, team, season)).status_code == 201
        resp = await _create(client, auth_headers, team, season)
        assert resp.status_code == 409
        assert "Hard print limit reached" in resp.json()["message"]

        quota = await client.get(
            "/api/printing/quotas",
            headers=auth_headers,
            params={"team_id": team.id, "season_id": season.id},
        )
        assert quota.json()["open_parts"] == 4
        assert quota.json()["used_parts"] == 0

    @pytest.mark.asyncio
    async def test_rejected_and_cancelled_jobs_free_the_slot(
        self, client, auth_headers, team, season
    ):
        ids = [(await _create(client, auth_headers, team, season)).json()["id"] for _ in range(4)]
        await client.put(
            f"/api/printing/jobs/{ids[0]}/reject", headers=auth_headers, json={"reason": "too big"}
        )
        await client.put(f"/api/printing/jobs/{ids[1]}/cancel", headers=auth_headers)
        assert (await _create(client, auth_headers, team, season)).status_code == 201
        assert (await _create(client, auth_headers, team, season)).status_code == 201
        assert (await _create(client, auth_headers, team, season)).status_code == 409

    @pytest.mark.asyncio
    async def test_soft_limit_returns_warning(self, client, auth_headers, team, season):
        # soft_limit_parts == 3: the 4th part exceeds it but is accepted.
        for _ in range(3):
            resp = await _create(client, auth_headers, team, season)
            assert resp.json()["quota_warning"] is None
        resp = await _create(client, auth_headers, team, season)
        assert resp.status_code == 201
        assert "Soft limit exceeded" in resp.json()["quota_warning"]

    @pytest.mark.asyncio
    async def test_max_grams_enforced_with_estimate(self, client, auth_headers, team, season):
        await client.put(
            "/api/printing/quotas",
            headers=auth_headers,
            json={"team_id": team.id, "season_id": season.id, "max_grams": 100, "max_parts": 10},
        )
        assert (
            await _create(client, auth_headers, team, season, estimated_grams=60)
        ).status_code == 201
        blocked = await _create(client, auth_headers, team, season, estimated_grams=50)
        assert blocked.status_code == 409
        assert "Filament limit" in blocked.json()["message"]
        # Without an estimate the gram limit cannot be judged up front.
        assert (await _create(client, auth_headers, team, season)).status_code == 201

    @pytest.mark.asyncio
    async def test_completed_grams_count_toward_max_grams(self, client, auth_headers, team, season):
        await client.put(
            "/api/printing/quotas",
            headers=auth_headers,
            json={"team_id": team.id, "season_id": season.id, "max_grams": 100, "max_parts": 10},
        )
        job = (await _create(client, auth_headers, team, season)).json()
        await _complete(client, auth_headers, job["id"], actual_grams=90)
        resp = await _create(client, auth_headers, team, season, estimated_grams=20)
        assert resp.status_code == 409

    @pytest.mark.asyncio
    async def test_admin_override_is_recorded(self, client, auth_headers, team, season, db):
        for _ in range(4):
            await _create(client, auth_headers, team, season)
        resp = await _create(client, auth_headers, team, season, quota_override=True)
        assert resp.status_code == 201, resp.text
        body = resp.json()
        assert body["quota_override"] is True
        assert "override" in body["quota_warning"]
        await db.flush()  # the test session does not autoflush
        audit = (
            await db.execute(select(AuditLog).where(AuditLog.action == "printing.quota_override"))
        ).scalar_one()
        assert audit.resource_id == body["id"]

    @pytest.mark.asyncio
    async def test_override_not_flagged_when_within_limits(
        self, client, auth_headers, team, season
    ):
        resp = await _create(client, auth_headers, team, season, quota_override=True)
        assert resp.json()["quota_override"] is False

    @pytest.mark.asyncio
    async def test_mentor_cannot_override(self, client, db, team, season):
        _, mentor = await _mentor(db, team, MENTOR_PERMS)
        resp = await _create(client, mentor, team, season, quota_override=True)
        assert resp.status_code == 403

    @pytest.mark.asyncio
    async def test_set_quota_with_several_events(self, client, auth_headers, team, season, db):
        from modules.events.models import Event

        second = Event(season_id=season.id, name="GCER", slug="gcer-quota", status="published")
        db.add(second)
        await db.commit()
        # Rows for both events exist, which used to break the season lookup.
        for event_id in (None, second.id):
            params = {"team_id": team.id, "season_id": season.id}
            if event_id:
                params["event_id"] = event_id
            assert (
                await client.get("/api/printing/quotas", headers=auth_headers, params=params)
            ).status_code == 200

        resp = await client.put(
            "/api/printing/quotas",
            headers=auth_headers,
            json={
                "team_id": team.id,
                "season_id": season.id,
                "event_id": second.id,
                "max_parts": 9,
            },
        )
        assert resp.status_code == 200, resp.text
        assert resp.json()["event_id"] == second.id
        default = await client.put(
            "/api/printing/quotas",
            headers=auth_headers,
            json={"team_id": team.id, "season_id": season.id, "max_parts": 2},
        )
        assert default.status_code == 200
        assert default.json()["event_id"] != second.id

        rows = (
            await db.execute(
                select(TeamSeasonPrintQuota).where(TeamSeasonPrintQuota.team_id == team.id)
            )
        ).scalars()
        by_event = {row.event_id: row.max_parts for row in rows}
        assert by_event[second.id] == 9
        assert sorted(by_event.values()) == [2, 9]

    @pytest.mark.asyncio
    async def test_clear_max_grams(self, client, auth_headers, team, season):
        body = {"team_id": team.id, "season_id": season.id}
        await client.put(
            "/api/printing/quotas", headers=auth_headers, json={**body, "max_grams": 5}
        )
        resp = await client.put(
            "/api/printing/quotas", headers=auth_headers, json={**body, "clear_max_grams": True}
        )
        assert resp.json()["max_grams"] is None

    @pytest.mark.asyncio
    async def test_event_quota_listing(self, client, auth_headers, team, season, event, db):
        from modules.events.models import EventRegistration

        db.add(EventRegistration(event_id=event.id, team_id=team.id))
        await db.commit()
        resp = await client.get(f"/api/printing/events/{event.id}/quotas", headers=auth_headers)
        assert resp.status_code == 200
        assert [(q["team_id"], q["team_name"]) for q in resp.json()] == [(team.id, team.name)]

    @pytest.mark.asyncio
    async def test_event_quota_listing_admin_only(self, client, db, team, event):
        _, mentor = await _mentor(db, team, MENTOR_PERMS)
        resp = await client.get(f"/api/printing/events/{event.id}/quotas", headers=mentor)
        assert resp.status_code == 403


# ── Reject / cancel ─────────────────────────────────────────────────────────


class TestRejectAndCancel:
    @pytest.mark.asyncio
    async def test_reject_with_reason(self, client, auth_headers, team, season):
        job = (await _create(client, auth_headers, team, season)).json()
        resp = await client.put(
            f"/api/printing/jobs/{job['id']}/reject",
            headers=auth_headers,
            json={"reason": "Overhangs need supports"},
        )
        assert resp.status_code == 200
        assert resp.json()["status"] == "rejected"
        assert resp.json()["rejection_reason"] == "Overhangs need supports"
        # Terminal: neither approval nor a second rejection is possible.
        assert (
            await client.put(f"/api/printing/jobs/{job['id']}/approve", headers=auth_headers)
        ).status_code == 409

    @pytest.mark.asyncio
    async def test_reject_requires_reason(self, client, auth_headers, team, season):
        job = (await _create(client, auth_headers, team, season)).json()
        resp = await client.put(
            f"/api/printing/jobs/{job['id']}/reject", headers=auth_headers, json={"reason": ""}
        )
        assert resp.status_code == 422

    @pytest.mark.asyncio
    async def test_cannot_reject_printing_job(self, client, auth_headers, team, season):
        job = (await _create(client, auth_headers, team, season)).json()
        await client.put(f"/api/printing/jobs/{job['id']}/approve", headers=auth_headers)
        for status in ("queued", "printing"):
            await client.patch(
                f"/api/printing/jobs/{job['id']}", headers=auth_headers, json={"status": status}
            )
        resp = await client.put(
            f"/api/printing/jobs/{job['id']}/reject", headers=auth_headers, json={"reason": "x"}
        )
        assert resp.status_code == 409

    @pytest.mark.asyncio
    async def test_mentor_cannot_reject(self, client, db, team, season):
        _, mentor = await _mentor(db, team, MENTOR_PERMS)
        job = (await _create(client, mentor, team, season)).json()
        resp = await client.put(
            f"/api/printing/jobs/{job['id']}/reject", headers=mentor, json={"reason": "x"}
        )
        assert resp.status_code == 403

    @pytest.mark.asyncio
    async def test_mentor_cancels_own_pending_job_only(
        self, client, db, team, rival, season, auth_headers
    ):
        _, mentor = await _mentor(db, team, MENTOR_PERMS)
        pending = (await _create(client, mentor, team, season)).json()
        approved = (await _create(client, mentor, team, season)).json()
        foreign = (await _create(client, auth_headers, rival, season)).json()
        await client.put(f"/api/printing/jobs/{approved['id']}/approve", headers=auth_headers)

        ok = await client.put(f"/api/printing/jobs/{pending['id']}/cancel", headers=mentor)
        assert ok.status_code == 200
        assert ok.json()["status"] == "cancelled"
        late = await client.put(f"/api/printing/jobs/{approved['id']}/cancel", headers=mentor)
        assert late.status_code == 409
        other = await client.put(f"/api/printing/jobs/{foreign['id']}/cancel", headers=mentor)
        assert other.status_code == 404

    @pytest.mark.asyncio
    async def test_admin_cancels_any_open_job(self, client, auth_headers, team, season):
        job = (await _create(client, auth_headers, team, season)).json()
        await client.put(f"/api/printing/jobs/{job['id']}/approve", headers=auth_headers)
        await client.patch(
            f"/api/printing/jobs/{job['id']}", headers=auth_headers, json={"status": "queued"}
        )
        resp = await client.put(f"/api/printing/jobs/{job['id']}/cancel", headers=auth_headers)
        assert resp.json()["status"] == "cancelled"
        again = await client.put(f"/api/printing/jobs/{job['id']}/cancel", headers=auth_headers)
        assert again.status_code == 409

    @pytest.mark.asyncio
    async def test_patch_cannot_set_rejected(self, client, auth_headers, team, season):
        job = (await _create(client, auth_headers, team, season)).json()
        resp = await client.patch(
            f"/api/printing/jobs/{job['id']}", headers=auth_headers, json={"status": "rejected"}
        )
        assert resp.status_code == 422


# ── Printers ────────────────────────────────────────────────────────────────


class TestPrinterVisibility:
    @pytest.mark.asyncio
    async def test_generic_printer_type_is_accepted(self, client, auth_headers):
        resp = await client.post(
            "/api/printing/printers",
            headers=auth_headers,
            json={"name": "Ender manual", "printer_type": "generic"},
        )
        assert resp.status_code == 201
        assert resp.json()["printer_type"] == "generic"

    @pytest.mark.asyncio
    async def test_mentor_sees_status_without_connection_details(
        self, client, db, team, auth_headers
    ):
        await client.post(
            "/api/printing/printers",
            headers=auth_headers,
            json={
                "name": "Bambu",
                "printer_type": "bambu",
                "api_url": "10.0.0.5",
                "device_id": "SERIAL123",
                "api_key": "access-code",
                "notes": "shelf 2",
            },
        )
        _, mentor = await _mentor(db, team, ["printing:read"])
        resp = await client.get("/api/printing/printers", headers=mentor)
        assert resp.status_code == 200
        [printer] = resp.json()
        assert printer["name"] == "Bambu"
        assert printer["api_url"] is None
        assert printer["device_id"] is None
        assert printer["notes"] is None
        for secret in ("10.0.0.5", "SERIAL123", "access-code", "shelf 2"):
            assert secret not in resp.text

        admin_view = (await client.get("/api/printing/printers", headers=auth_headers)).json()
        assert admin_view[0]["api_url"] == "10.0.0.5"


# ── Filament ────────────────────────────────────────────────────────────────


class TestFilamentOnCompletion:
    async def _spool(self, client, headers, grams=1000.0):
        resp = await client.post(
            "/api/printing/spools",
            headers=headers,
            json={"material": "PLA", "initial_grams": grams},
        )
        return resp.json()["id"]

    async def _remaining(self, client, headers, spool_id):
        spools = (await client.get("/api/printing/spools", headers=headers)).json()
        return next(s["remaining_grams"] for s in spools if s["id"] == spool_id)

    @pytest.mark.asyncio
    async def test_completion_deducts_from_chosen_spool(self, client, auth_headers, team, season):
        spool = await self._spool(client, auth_headers)
        job = (await _create(client, auth_headers, team, season)).json()
        resp = await _complete(client, auth_headers, job["id"], actual_grams=42.5, spool_id=spool)
        assert resp.status_code == 200
        assert resp.json()["spool_id"] == spool
        assert await self._remaining(client, auth_headers, spool) == pytest.approx(957.5)

    @pytest.mark.asyncio
    async def test_grams_entered_after_auto_completion(self, client, auth_headers, team, season):
        spool = await self._spool(client, auth_headers)
        job = (await _create(client, auth_headers, team, season)).json()
        await _complete(client, auth_headers, job["id"])  # e.g. by the printer poller
        await client.patch(
            f"/api/printing/jobs/{job['id']}",
            headers=auth_headers,
            json={"actual_grams": 30, "spool_id": spool},
        )
        assert await self._remaining(client, auth_headers, spool) == pytest.approx(970)
        # A correction books only the difference, on quota and spool.
        await client.patch(
            f"/api/printing/jobs/{job['id']}", headers=auth_headers, json={"actual_grams": 25}
        )
        assert await self._remaining(client, auth_headers, spool) == pytest.approx(975)
        quota = await client.get(
            "/api/printing/quotas",
            headers=auth_headers,
            params={"team_id": team.id, "season_id": season.id},
        )
        assert quota.json()["used_grams"] == pytest.approx(25)
        assert quota.json()["used_parts"] == 1

    @pytest.mark.asyncio
    async def test_switching_spool_refunds_the_old_one(self, client, auth_headers, team, season):
        first = await self._spool(client, auth_headers)
        second = await self._spool(client, auth_headers)
        job = (await _create(client, auth_headers, team, season)).json()
        await _complete(client, auth_headers, job["id"], actual_grams=40, spool_id=first)
        await client.patch(
            f"/api/printing/jobs/{job['id']}", headers=auth_headers, json={"spool_id": second}
        )
        assert await self._remaining(client, auth_headers, first) == pytest.approx(1000)
        assert await self._remaining(client, auth_headers, second) == pytest.approx(960)

    @pytest.mark.asyncio
    async def test_unknown_spool_is_404(self, client, auth_headers, team, season):
        job = (await _create(client, auth_headers, team, season)).json()
        resp = await client.patch(
            f"/api/printing/jobs/{job['id']}", headers=auth_headers, json={"spool_id": "nope"}
        )
        assert resp.status_code == 404

    @pytest.mark.asyncio
    async def test_grams_not_booked_before_completion(self, client, auth_headers, team, season):
        spool = await self._spool(client, auth_headers)
        job = (await _create(client, auth_headers, team, season)).json()
        await client.patch(
            f"/api/printing/jobs/{job['id']}",
            headers=auth_headers,
            json={"actual_grams": 10, "spool_id": spool},
        )
        assert await self._remaining(client, auth_headers, spool) == pytest.approx(1000)
